# Generated by Django 4.2.2 on 2023-06-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=250)),
                ('pimg', models.ImageField(upload_to='team')),
                ('pdesc', models.TextField()),
            ],
        ),
    ]
